// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64            `json:"id"`
	Owner     string           `json:"owner"`
	Balance   int64            `json:"balance"`
	Currency  string           `json:"currency"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AcoountID int64 `json:"acoount_id"`
	// can be positive or negetive
	Ammount   int64            `json:"ammount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID            int64 `json:"id"`
	FromAcoountID int64 `json:"from_acoount_id"`
	ToAcoountID   int64 `json:"to_acoount_id"`
	// must be positive
	Ammount   int64            `json:"ammount"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
